window.AUDIO = {
    "Guten Tag, herzlich willkommen im Camping Beach Garden!":  "audio/a0001.mp3",
    "Ihren Namen, bitte?":  "audio/a0002.mp3",
    "Was ist Ihr Ankunftsdatum?":  "audio/a0003.mp3",
    "Wie viele Nächte bleiben Sie bei uns?":  "audio/a0004.mp3",
    "Hier ist Ihr Zugangsarmband.":  "audio/a0005.mp3",
    "Hier ist der Campingplan.":  "audio/a0006.mp3",
    "Ihr Stellplatz hat die Nummer…":  "audio/a0007.mp3",
    "Sie können Ihr Fahrzeug ab zwölf Uhr abstellen. Der Stellplatz ist ab vierzehn Uhr garantiert, und das Mobilheim ab siebzehn Uhr.":  "audio/a0008.mp3",
    "Die Abreise ist vor elf Uhr auf dem Stellplatz, und vor zehn Uhr im Mobilheim.":  "audio/a0009.mp3",
    "Wir wünschen Ihnen einen schönen Aufenthalt!":  "audio/a0010.mp3",
    "Haben Sie ein Auto dabei?":  "audio/a0011.mp3",
    "Wie lautet Ihre Bestätigungs-E-Mail-Adresse?":  "audio/a0012.mp3",
    "Ihr Mobilheim hat eine Terrasse.":  "audio/a0013.mp3",
    "Das Mobilheim hat eine Klimaanlage.":  "audio/a0014.mp3",
    "Die Küche ist vollständig ausgestattet.":  "audio/a0015.mp3",
    "Ihr Zelt- oder Wohnmobil-Stellplatz.":  "audio/a0016.mp3",
    "Der Stromanschluss ist inklusive.":  "audio/a0017.mp3",
    "Dieses Mobilheim ist für vier Personen.":  "audio/a0018.mp3",
    "Das Maison des Sables liegt direkt am Meer.":  "audio/a0019.mp3",
    "Bettwäsche und Handtücher sind inklusive.":  "audio/a0020.mp3",
    "Hunde sind erlaubt: sieben Euro pro Tag auf dem Stellplatz, neun Euro in der Mietunterkunft.":  "audio/a0146.mp3",
    "Das Mobilheim hat einen Fernseher.":  "audio/a0022.mp3",
    "Haben Sie eine Reservierung?":  "audio/a0023.mp3",
    "Ihre Reservierung ist bestätigt.":  "audio/a0024.mp3",
    "Der Preis beträgt … Euro pro Nacht.":  "audio/a0025.mp3",
    "Akzeptieren Sie Kreditkarte?":  "audio/a0026.mp3",
    "Kostenlose Stornierung bis sieben Tage vor der Anreise.":  "audio/a0027.mp3",
    "Eine Anzahlung von dreißig Prozent ist erforderlich.":  "audio/a0028.mp3",
    "Wann reisen Sie ab?":  "audio/a0029.mp3",
    "Möchten Sie Ihren Aufenthalt verlängern?":  "audio/a0030.mp3",
    "Das Schwimmbad ist von neun bis neunzehn Uhr geöffnet.":  "audio/a0031.mp3",
    "Der Wasserpark ist kostenlos.":  "audio/a0032.mp3",
    "Die Rutschen sind nachmittags geöffnet.":  "audio/a0033.mp3",
    "Badehosen sind Pflicht. Badeshorts sind nicht erlaubt.":  "audio/a0034.mp3",
    "Das Hallenbad ist beheizt.":  "audio/a0035.mp3",
    "Das Planschbecken ist für Kleinkinder.":  "audio/a0036.mp3",
    "Der Spa und der Whirlpool befinden sich im Bulle des Sables.":  "audio/a0037.mp3",
    "Die Duschen befinden sich neben dem Schwimmbad.":  "audio/a0038.mp3",
    "Der Strandzugang ist direkt vom Campinggelände aus.":  "audio/a0039.mp3",
    "Der Strand wird von zehn bis achtzehn Uhr bewacht.":  "audio/a0040.mp3",
    "Liegestühle können gegen eine Gebühr gemietet werden.":  "audio/a0041.mp3",
    "Vorsicht, heute gibt es Quallen im Meer.":  "audio/a0042.mp3",
    "Rote Fahne bedeutet, Schwimmen ist verboten.":  "audio/a0043.mp3",
    "Das Mittelmeer ist wunderschön!":  "audio/a0044.mp3",
    "Ein Radweg verläuft entlang der Küste.":  "audio/a0045.mp3",
    "Der Sand ist fein und warm.":  "audio/a0046.mp3",
    "Das WLAN ist überall auf dem Campinggelände verfügbar.":  "audio/a0047.mp3",
    "Das WLAN ist kostenpflichtig. Fragen Sie an der Rezeption nach dem Code.":  "audio/a0048.mp3",
    "Das Restaurant ist abends ab neunzehn Uhr geöffnet.":  "audio/a0049.mp3",
    "Die Bäckerei öffnet um acht Uhr.":  "audio/a0050.mp3",
    "Der Campingmarkt ist von acht bis zwanzig Uhr geöffnet.":  "audio/a0051.mp3",
    "Die Sanitäranlagen befinden sich auf Ihrer rechten Seite.":  "audio/a0052.mp3",
    "Die Waschküche befindet sich im Zentralgebäude.":  "audio/a0053.mp3",
    "Sie können hier Fahrräder ausleihen.":  "audio/a0054.mp3",
    "In der Saison gibt es jeden Abend Unterhaltungsprogramm.":  "audio/a0055.mp3",
    "Der Kinderclub nimmt Kinder von fünf bis zwölf Jahren auf.":  "audio/a0056.mp3",
    "Der Spa bietet Massagen und ein Hammam an.":  "audio/a0057.mp3",
    "Sie haben Zugang zu allen drei Campings.":  "audio/a0058.mp3",
    "Der Parkplatz befindet sich am Eingang des Campings.":  "audio/a0059.mp3",
    "Ab zweiundzwanzig Uhr gilt Nachtruhe auf dem Camping.":  "audio/a0060.mp3",
    "Die Höchstgeschwindigkeit beträgt zehn Kilometer pro Stunde.":  "audio/a0061.mp3",
    "Das Armband muss jederzeit getragen werden.":  "audio/a0062.mp3",
    "Die Mülleimer befinden sich am Eingang des Campings.":  "audio/a0063.mp3",
    "Bitte trennen Sie Ihren Abfall.":  "audio/a0064.mp3",
    "Nur Elektrogrills sind erlaubt.":  "audio/a0147.mp3",
    "Kinder müssen nachts von Erwachsenen begleitet werden.":  "audio/a0066.mp3",
    "Im Notfall rufen Sie bitte fünfzehn oder achtzehn an.":  "audio/a0067.mp3",
    "Ich rufe sofort den Notdienst an.":  "audio/a0068.mp3",
    "Die nächste Apotheke ist fünfhundert Meter entfernt.":  "audio/a0069.mp3",
    "Ich schicke jemanden vorbei, um das zu reparieren.":  "audio/a0070.mp3",
    "Bitte drehen Sie die Musik leiser.":  "audio/a0071.mp3",
    "Bei einem Diebstahl rufen Sie bitte die siebzehn an.":  "audio/a0072.mp3",
    "Ich habe mein Armband verloren.":  "audio/a0073.mp3",
    "Im Mobilheim gibt es kein warmes Wasser.":  "audio/a0074.mp3",
    "Das Dorf Marseillan liegt sieben Kilometer entfernt.":  "audio/a0075.mp3",
    "Sète und sein Kanal sind sehr malerisch.":  "audio/a0076.mp3",
    "Ein Radweg führt bis nach Marseillan.":  "audio/a0077.mp3",
    "Den Noilly Prat kann man im Hafen von Marseillan probieren.":  "audio/a0078.mp3",
    "Cap d\u0027Agde ist zehn Minuten mit dem Auto entfernt.":  "audio/a0079.mp3",
    "Der Thau-See ist nur wenige Minuten entfernt.":  "audio/a0080.mp3",
    "Die Austern aus dem Thau-See sind köstlich.":  "audio/a0081.mp3",
    "Der Markt von Marseillan findet dienstags morgens statt.":  "audio/a0082.mp3",
    "Guten Morgen! Guten Tag!":  "audio/a0083.mp3",
    "Gute Nacht!":  "audio/a0084.mp3",
    "Auf Wiedersehen und gute Weiterreise!":  "audio/a0085.mp3",
    "Vielen Dank!":  "audio/a0086.mp3",
    "Ich verstehe leider kein Deutsch.":  "audio/a0087.mp3",
    "Sprechen Sie Französisch?":  "audio/a0088.mp3",
    "Sprechen Sie Englisch?":  "audio/a0089.mp3",
    "Einen Moment bitte.":  "audio/a0090.mp3",
    "Folgen Sie mir, ich zeige es Ihnen.":  "audio/a0091.mp3",
    "Haben Sie noch weitere Fragen?":  "audio/a0092.mp3",
    "Ich wünsche Ihnen einen schönen Urlaub!":  "audio/a0093.mp3",
    "Könnten Sie das bitte wiederholen?":  "audio/a0094.mp3",
    "Der Campingplatz ist von April bis Oktober geöffnet.":  "audio/a0148.mp3",
    "Die Cabane Réserve bietet Platz für vier bis sechs Personen.":  "audio/a0149.mp3",
    "Das Garden Family ist für sechs bis acht Personen.":  "audio/a0150.mp3",
    "Die Villa La Coquille hat ihren eigenen privaten Pool.":  "audio/a0151.mp3",
    "Bettwäsche und Handtücher sind inklusive, außer in der Cosy-Kategorie.":  "audio/a0152.mp3",
    "Bei früher Buchung erhalten Sie zehn Prozent Rabatt.":  "audio/a0153.mp3",
    "Der große Pool im Beach Garden ist dreiunddreißig Meter lang.":  "audio/a0154.mp3",
    "Der überdachte Wellnessbereich bietet ruhiges oder sprudelndes Wasser.":  "audio/a0155.mp3",
    "Das Restaurant Le Bistro hat einen Panoramablick auf das Meer.":  "audio/a0156.mp3",
    "In den Gemeinschaftsbereichen ist das WLAN kostenlos.":  "audio/a0157.mp3",
    "Das Spa Bulle des Sables bietet Hammam, Sauna, Massagen und ein Nagelstudio.":  "audio/a0158.mp3",
    "Es gibt Beachvolleyball und Aquagym.":  "audio/a0159.mp3",
    "Es gibt einen Miniclub für Kinder und einen Club für Jugendliche.":  "audio/a0160.mp3",
    "Jeder Besucher muss sich an der Rezeption melden; nach zwei Stunden wird eine Gebühr fällig.":  "audio/a0161.mp3",
    "In Bouzigues isst man Austern direkt am Thau-See.":  "audio/a0162.mp3",
    "Guten Tag, ich hätte gerne einen Stellplatz für ein Wohnmobil.":  "audio/a0095.mp3",
    "Haben Sie einen Platz für unseren Wohnwagen?":  "audio/a0096.mp3",
    "Guten Tag, sehr gut! Waren Sie schon einmal bei uns?":  "audio/a0097.mp3",
    "Haben Sie eine ACSI-, ADAC- oder ANWB-Karte?":  "audio/a0098.mp3",
    "Wie ist Ihr Nachname, bitte?":  "audio/a0099.mp3",
    "Hier ist der Plan mit den freien Plätzen. Wenn eine Nummer steht, ist der Platz frei. Ohne Nummer ist er belegt.":  "audio/a0100.mp3",
    "Nehmen Sie den Plan, gehen Sie zu Fuß hin, und kommen Sie zurück, wenn Sie zwei ausgewählt haben.":  "audio/a0101.mp3",
    "Hier ist der Bereich für die ACSI-Stellplätze.":  "audio/a0102.mp3",
    "Ich behalte Ihre ACSI-Karte oder Ihren Ausweis, und Sie zahlen am Tag vor Ihrer Abreise. So zahlen Sie nur die Tage, die Sie bleiben!":  "audio/a0103.mp3",
    "Wie viele Erwachsene und wie viele Kinder sind Sie?":  "audio/a0104.mp3",
    "Haben Sie einen Hund dabei?":  "audio/a0105.mp3",
    "Ich brauche bitte Ihr Kennzeichen.":  "audio/a0106.mp3",
    "Ihre Telefonnummer, bitte?":  "audio/a0107.mp3",
    "Ihre E-Mail-Adresse?":  "audio/a0108.mp3",
    "Und Ihre Wohnadresse, bitte?":  "audio/a0109.mp3",
    "Wir sind hier an der Rezeption vom Beach Garden. Daneben ist der Nouvelle Floride, und gegenüber der Charlemagne. Mit Ihren Armbändern haben Sie vollen Zugang zu allen drei Campings!":  "audio/a0110.mp3",
    "Hier sperrt eine Tür den Zugang zum Strand. Sie geben diesen Code ein, um sie zu öffnen. Sie funktioniert von sieben bis zweiundzwanzig Uhr.":  "audio/a0111.mp3",
    "Ich empfehle Ihnen, die App Tipiz herunterzuladen. Sie geben dieses Passwort ein. Darin finden Sie das Animationsprogramm, die Öffnungszeiten, die Menüs, das Wetter und mehr.":  "audio/a0112.mp3",
    "Hier sind Ihre Armbänder: diese für die Erwachsenen, und diese für die Minderjährigen.":  "audio/a0113.mp3",
    "Und diese Vignette legen Sie bitte auf das Armaturenbrett Ihres Fahrzeugs.":  "audio/a0114.mp3",
    "Haben Sie noch Fragen?":  "audio/a0115.mp3",
    "Perfekt! Ich wünsche Ihnen einen schönen Aufenthalt bei uns.":  "audio/a0116.mp3",
    "Guten Morgen, wir reisen heute ab.":  "audio/a0117.mp3",
    "Wir möchten gerne auschecken.":  "audio/a0118.mp3",
    "Guten Morgen! Ich hoffe, Sie hatten einen schönen Aufenthalt. Haben Sie das Mobilheim aufgeräumt?":  "audio/a0119.mp3",
    "Haben Sie die Endreinigung gemacht, oder sollen wir das übernehmen?":  "audio/a0120.mp3",
    "Können Sie mir bitte die Armbänder und den Schlüssel zurückgeben?":  "audio/a0121.mp3",
    "Alles ist in Ordnung, Sie bekommen Ihre Kaution zurück.":  "audio/a0122.mp3",
    "Vielen Dank für alles, es war wunderschön!":  "audio/a0123.mp3",
    "Können wir schon für nächstes Jahr buchen?":  "audio/a0124.mp3",
    "Vielen Dank für Ihren Besuch und gute Heimreise! Bis nächstes Jahr, hoffentlich.":  "audio/a0125.mp3",
    "Die Nachbarn sind viel zu laut, wir können nicht schlafen.":  "audio/a0126.mp3",
    "Können Sie bitte etwas unternehmen?":  "audio/a0127.mp3",
    "Es tut mir wirklich leid für die Störung. Ich kümmere mich sofort darum.":  "audio/a0128.mp3",
    "Ab zweiundzwanzig Uhr gilt bei uns Nachtruhe. Darf ich Sie bitten, leiser zu sein?":  "audio/a0129.mp3",
    "Es ist erledigt, sie werden Rücksicht nehmen. Kommen Sie gerne wieder zu mir, falls es noch einmal passiert.":  "audio/a0130.mp3",
    "Die Klimaanlage funktioniert nicht.":  "audio/a0131.mp3",
    "Oh, das tut mir leid. Können Sie mir Ihre Stellplatznummer geben?":  "audio/a0132.mp3",
    "Ich schicke Ihnen so schnell wie möglich einen Techniker vorbei.":  "audio/a0133.mp3",
    "Er kommt innerhalb einer Stunde vorbei.":  "audio/a0134.mp3",
    "Funktioniert jetzt wieder alles?":  "audio/a0135.mp3",
    "Entschuldigen Sie bitte die Unannehmlichkeiten.":  "audio/a0136.mp3",
    "Camping Beach Garden, guten Tag! Was kann ich für Sie tun?":  "audio/a0137.mp3",
    "Ich möchte einen Stellplatz reservieren.":  "audio/a0138.mp3",
    "Haben Sie im August noch etwas frei?":  "audio/a0139.mp3",
    "Für welche Daten möchten Sie reservieren?":  "audio/a0140.mp3",
    "Wie viele Personen sind Sie?":  "audio/a0141.mp3",
    "Möchten Sie lieber einen Stellplatz oder ein Mobilheim?":  "audio/a0142.mp3",
    "Der Preis beträgt … Euro pro Nacht. Wir benötigen eine Anzahlung von dreißig Prozent.":  "audio/a0143.mp3",
    "Ich sende Ihnen die Bestätigung per E-Mail. Wie lautet Ihre E-Mail-Adresse?":  "audio/a0144.mp3",
    "Vielen Dank für Ihren Anruf und bis bald im Beach Garden!":  "audio/a0145.mp3"
};
