window.AUDIO = {
    "Guten Tag und herzlich willkommen auf dem Campingplatz Beach Garden!":  "audio/a0225.mp3",
    "Ihren Namen, bitte?":  "audio/a0002.mp3",
    "Was ist Ihr Ankunftsdatum?":  "audio/a0003.mp3",
    "Wie viele Nächte bleiben Sie bei uns?":  "audio/a0004.mp3",
    "Hier ist Ihr Zugangsarmband.":  "audio/a0005.mp3",
    "Hier ist der Campingplan.":  "audio/a0006.mp3",
    "Ihr Stellplatz hat die Nummer…":  "audio/a0007.mp3",
    "Sie können Ihr Fahrzeug ab zwölf Uhr abstellen. Der Stellplatz ist spätestens um vierzehn Uhr fertig, das Mobilheim spätestens um siebzehn Uhr.":  "audio/a0271.mp3",
    "Die Abreise erfolgt zwischen sieben und elf Uhr auf dem Stellplatz und zwischen sieben und zehn Uhr im Mobilheim.":  "audio/a0272.mp3",
    "Wir wünschen Ihnen einen schönen Aufenthalt!":  "audio/a0010.mp3",
    "Haben Sie ein Auto dabei?":  "audio/a0011.mp3",
    "Wie lautet Ihre Bestätigungs-E-Mail-Adresse?":  "audio/a0012.mp3",
    "Ihr Mobilheim hat eine Terrasse.":  "audio/a0013.mp3",
    "Das Mobilheim hat eine Klimaanlage.":  "audio/a0014.mp3",
    "Die Küche ist vollständig ausgestattet.":  "audio/a0015.mp3",
    "Ihr Zelt- oder Wohnmobil-Stellplatz.":  "audio/a0016.mp3",
    "Der Stromanschluss ist inklusive.":  "audio/a0017.mp3",
    "Dieses Mobilheim ist für vier Personen.":  "audio/a0018.mp3",
    "Das Maison des Sables liegt direkt am Meer.":  "audio/a0019.mp3",
    "Bettwäsche und Handtücher sind inklusive.":  "audio/a0020.mp3",
    "Hunde sind erlaubt: sieben Euro pro Tag auf dem Stellplatz, neun Euro in der Mietunterkunft.":  "audio/a0146.mp3",
    "Wir haben Standard-Stellplätze, Komfort-Stellplätze sowie Stellplätze in zweiter und in erster Reihe.":  "audio/a0228.mp3",
    "Das Mobilheim hat einen Fernseher.":  "audio/a0022.mp3",
    "Haben Sie eine Reservierung?":  "audio/a0023.mp3",
    "Ihre Reservierung ist bestätigt.":  "audio/a0024.mp3",
    "Der Preis beträgt … Euro pro Nacht.":  "audio/a0025.mp3",
    "Zahlen Sie mit Karte oder bar?":  "audio/a0229.mp3",
    "Kostenlose Stornierung bis sieben Tage vor der Anreise.":  "audio/a0027.mp3",
    "Eine Anzahlung von dreißig Prozent ist erforderlich.":  "audio/a0028.mp3",
    "Wann reisen Sie ab?":  "audio/a0029.mp3",
    "Möchten Sie Ihren Aufenthalt verlängern?":  "audio/a0030.mp3",
    "Das Schwimmbad ist von neun bis neunzehn Uhr geöffnet.":  "audio/a0031.mp3",
    "Der Wasserpark ist kostenlos.":  "audio/a0032.mp3",
    "Die Rutschen sind nachmittags geöffnet.":  "audio/a0033.mp3",
    "Badehosen sind Pflicht. Badeshorts sind nicht erlaubt.":  "audio/a0034.mp3",
    "Das Hallenbad ist beheizt.":  "audio/a0035.mp3",
    "Das Planschbecken ist für Kleinkinder.":  "audio/a0036.mp3",
    "Das Spa und der Whirlpool befinden sich im Bulle des Sables.":  "audio/a0230.mp3",
    "Die Duschen befinden sich neben dem Schwimmbad.":  "audio/a0038.mp3",
    "Der Strandzugang ist direkt vom Campinggelände aus.":  "audio/a0039.mp3",
    "Der Strand wird von zehn bis achtzehn Uhr bewacht.":  "audio/a0040.mp3",
    "Liegestühle können gegen eine Gebühr gemietet werden.":  "audio/a0041.mp3",
    "Vorsicht, heute gibt es Quallen im Meer.":  "audio/a0042.mp3",
    "Rote Flagge bedeutet: Baden verboten.":  "audio/a0231.mp3",
    "Das Mittelmeer ist wunderschön!":  "audio/a0044.mp3",
    "Ein Radweg verläuft entlang der Küste.":  "audio/a0045.mp3",
    "Der Sand ist fein und warm.":  "audio/a0046.mp3",
    "Das WLAN ist in allen Mobilheimen inklusive, außer in der Cosy-Kategorie.":  "audio/a0232.mp3",
    "Auf den Stellplätzen ist das WLAN kostenpflichtig. Fragen Sie an der Rezeption nach dem Code.":  "audio/a0233.mp3",
    "Das Restaurant ist abends ab neunzehn Uhr geöffnet.":  "audio/a0049.mp3",
    "Die Bäckerei öffnet um acht Uhr.":  "audio/a0050.mp3",
    "Der Campingmarkt ist von acht bis zwanzig Uhr geöffnet.":  "audio/a0051.mp3",
    "Die Sanitäranlagen befinden sich auf Ihrer rechten Seite.":  "audio/a0052.mp3",
    "Die Waschküche befindet sich im Zentralgebäude.":  "audio/a0053.mp3",
    "Sie können hier Fahrräder ausleihen.":  "audio/a0054.mp3",
    "In der Saison gibt es jeden Abend ein Unterhaltungsprogramm.":  "audio/a0234.mp3",
    "Der Kinderclub nimmt Kinder von fünf bis zwölf Jahren auf.":  "audio/a0056.mp3",
    "Das Spa bietet Massagen und ein Hammam an.":  "audio/a0235.mp3",
    "Sie haben Zugang zu allen drei Campingplätzen.":  "audio/a0236.mp3",
    "Der Parkplatz befindet sich am Eingang des Campingplatzes.":  "audio/a0237.mp3",
    "Ab zweiundzwanzig Uhr gilt Nachtruhe auf dem Campingplatz.":  "audio/a0238.mp3",
    "Die Höchstgeschwindigkeit beträgt zehn Kilometer pro Stunde.":  "audio/a0061.mp3",
    "Das Armband muss jederzeit getragen werden.":  "audio/a0062.mp3",
    "Die Mülleimer befinden sich am Eingang des Campingplatzes.":  "audio/a0239.mp3",
    "Bitte trennen Sie Ihren Abfall.":  "audio/a0064.mp3",
    "Nur Elektrogrills sind erlaubt.":  "audio/a0147.mp3",
    "Kinder müssen nachts von Erwachsenen begleitet werden.":  "audio/a0066.mp3",
    "Im Notfall rufen Sie bitte die Fünfzehn oder die Achtzehn an.":  "audio/a0240.mp3",
    "Ich rufe sofort den Notdienst an.":  "audio/a0068.mp3",
    "Die nächste Apotheke ist fünfhundert Meter entfernt.":  "audio/a0069.mp3",
    "Ich schicke jemanden vorbei, um das zu reparieren.":  "audio/a0070.mp3",
    "Bitte drehen Sie die Musik leiser.":  "audio/a0071.mp3",
    "Bei einem Diebstahl rufen Sie bitte die Siebzehn an.":  "audio/a0241.mp3",
    "Ich habe mein Armband verloren.":  "audio/a0073.mp3",
    "Im Mobilheim gibt es kein warmes Wasser.":  "audio/a0074.mp3",
    "Das Dorf Marseillan liegt sieben Kilometer entfernt.":  "audio/a0075.mp3",
    "Sète und sein Kanal sind sehr malerisch.":  "audio/a0076.mp3",
    "Ein Radweg führt bis nach Marseillan.":  "audio/a0077.mp3",
    "Den Noilly Prat kann man im Hafen von Marseillan probieren.":  "audio/a0078.mp3",
    "Cap d'Agde ist zehn Minuten mit dem Auto entfernt.":  "audio/a0079.mp3",
    "Der Thau-See ist nur wenige Minuten entfernt.":  "audio/a0080.mp3",
    "Die Austern aus dem Thau-See sind köstlich.":  "audio/a0081.mp3",
    "Der Markt von Marseillan findet dienstags morgens statt.":  "audio/a0082.mp3",
    "Guten Morgen! Guten Tag!":  "audio/a0083.mp3",
    "Gute Nacht!":  "audio/a0084.mp3",
    "Auf Wiedersehen und gute Weiterreise!":  "audio/a0085.mp3",
    "Vielen Dank!":  "audio/a0086.mp3",
    "Ich verstehe leider kein Deutsch.":  "audio/a0087.mp3",
    "Sprechen Sie Französisch?":  "audio/a0088.mp3",
    "Sprechen Sie Englisch?":  "audio/a0089.mp3",
    "Einen Moment bitte.":  "audio/a0090.mp3",
    "Haben Sie eine Frage?":  "audio/a0309.mp3",
    "Haben Sie noch weitere Fragen?":  "audio/a0092.mp3",
    "Ich wünsche Ihnen einen schönen Urlaub!":  "audio/a0093.mp3",
    "Könnten Sie das bitte wiederholen?":  "audio/a0094.mp3",
    "Der Campingplatz ist von April bis Oktober geöffnet.":  "audio/a0148.mp3",
    "Die Cabane Réserve bietet Platz für vier bis sechs Personen.":  "audio/a0149.mp3",
    "Das Garden Family ist für sechs bis acht Personen.":  "audio/a0150.mp3",
    "Die Villa La Coquille hat einen eigenen privaten Pool.":  "audio/a0242.mp3",
    "Bettwäsche und Handtücher sind inklusive, außer in der Cosy-Kategorie.":  "audio/a0152.mp3",
    "Bei früher Buchung erhalten Sie zehn Prozent Rabatt.":  "audio/a0153.mp3",
    "Der große Pool im Beach Garden ist dreiunddreißig Meter lang.":  "audio/a0154.mp3",
    "Der überdachte Wellnessbereich bietet ruhiges oder sprudelndes Wasser.":  "audio/a0155.mp3",
    "Das Restaurant Le Bistro hat einen Panoramablick auf das Meer.":  "audio/a0156.mp3",
    "An der Bar sind alle sechs Stunden dreißig Minuten WLAN gratis.":  "audio/a0243.mp3",
    "Das Spa Bulle des Sables bietet Hammam, Sauna, Massagen und ein Nagelstudio.":  "audio/a0158.mp3",
    "Es gibt Beachvolleyball und Aquagym.":  "audio/a0159.mp3",
    "Es gibt einen Miniclub für Kinder und einen Club für Jugendliche.":  "audio/a0160.mp3",
    "Jeder Besucher muss sich an der Rezeption melden; nach zwei Stunden wird eine Gebühr fällig.":  "audio/a0161.mp3",
    "In Bouzigues isst man Austern direkt am Thau-See.":  "audio/a0162.mp3",
    "Sie können spätestens bis dreiundzwanzig Uhr anreisen.":  "audio/a0247.mp3",
    "In der Mietunterkunft erfolgt die Abreise zwischen sieben und zehn Uhr. Nach zehn Uhr kann eine zusätzliche Nacht berechnet werden.":  "audio/a0273.mp3",
    "Sie erhalten die Kaution zurück, wenn die Unterkunft sauber und das Inventar vollständig ist.":  "audio/a0249.mp3",
    "Bei einer Buchung mehr als dreißig Tage vor der Anreise zahlen Sie dreißig Prozent an, bei weniger als dreißig Tagen den gesamten Betrag.":  "audio/a0250.mp3",
    "Änderungen müssen mindestens dreißig Tage vor der Anreise schriftlich beantragt werden, je nach Verfügbarkeit.":  "audio/a0251.mp3",
    "Die Kurtaxe wird von der Gemeinde festgelegt.":  "audio/a0252.mp3",
    "Erlaubt ist ein Hund oder zwei kleine Hunde unter zehn Kilo.":  "audio/a0253.mp3",
    "Hunde müssen an der Leine geführt werden und geimpft sein. Bitte zeigen Sie uns den Impfpass.":  "audio/a0254.mp3",
    "Für Damen ist ein Badeanzug oder ein Bikini erlaubt, für Herren eine Badehose.":  "audio/a0255.mp3",
    "Tiere sind im Poolbereich verboten.":  "audio/a0256.mp3",
    "Von dreiundzwanzig bis sieben Uhr ist die Einfahrt geschlossen und das Fahren verboten.":  "audio/a0257.mp3",
    "Pro Stellplatz ist nur ein Fahrzeug erlaubt; weitere Fahrzeuge parken bitte auf dem Parkplatz.":  "audio/a0258.mp3",
    "Holzkohlegrills sind streng verboten.":  "audio/a0259.mp3",
    "Für Besucher kostet der Zugang zu den Pools und zum Animationsprogramm zehn Euro pro Person und Tag.":  "audio/a0260.mp3",
    "Besucher müssen den Campingplatz spätestens um dreiundzwanzig Uhr verlassen.":  "audio/a0261.mp3",
    "Für das Mobilheim beträgt die Kaution dreihundert Euro, nur bar oder mit Karte.":  "audio/a0274.mp3",
    "Für die Stellplätze verleihen wir Stromadapter und Wasserkanister gegen eine Kaution von zwanzig Euro.":  "audio/a0275.mp3",
    "Brauchen Sie einen Stromadapter?":  "audio/a0276.mp3",
    "Wo sind die Toiletten?":  "audio/a0277.mp3",
    "Wann öffnet das Schwimmbad?":  "audio/a0278.mp3",
    "Wo können wir Brötchen kaufen?":  "audio/a0279.mp3",
    "Gibt es hier WLAN?":  "audio/a0280.mp3",
    "Wie lautet das WLAN-Passwort?":  "audio/a0281.mp3",
    "Wo ist der Strand?":  "audio/a0282.mp3",
    "Können wir später abreisen?":  "audio/a0283.mp3",
    "Wir haben den Schlüssel verloren.":  "audio/a0284.mp3",
    "Wo können wir unseren Müll entsorgen?":  "audio/a0285.mp3",
    "Haben Sie einen Adapter für den Strom?":  "audio/a0286.mp3",
    "Gibt es heute Abend eine Animation?":  "audio/a0287.mp3",
    "Wo ist der nächste Supermarkt?":  "audio/a0288.mp3",
    "Kann ich mit Karte bezahlen?":  "audio/a0289.mp3",
    "Das Mobilheim ist nicht sauber.":  "audio/a0290.mp3",
    "Die Dusche funktioniert nicht.":  "audio/a0291.mp3",
    "Wo können wir unser zweites Auto parken?":  "audio/a0292.mp3",
    "null":  "audio/a0163.mp3",
    "eins":  "audio/a0164.mp3",
    "zwei":  "audio/a0165.mp3",
    "drei":  "audio/a0166.mp3",
    "vier":  "audio/a0167.mp3",
    "fünf":  "audio/a0168.mp3",
    "sechs":  "audio/a0169.mp3",
    "sieben":  "audio/a0170.mp3",
    "acht":  "audio/a0171.mp3",
    "neun":  "audio/a0172.mp3",
    "zehn":  "audio/a0173.mp3",
    "elf":  "audio/a0174.mp3",
    "zwölf":  "audio/a0175.mp3",
    "dreizehn":  "audio/a0176.mp3",
    "vierzehn":  "audio/a0177.mp3",
    "fünfzehn":  "audio/a0178.mp3",
    "sechzehn":  "audio/a0179.mp3",
    "siebzehn":  "audio/a0180.mp3",
    "achtzehn":  "audio/a0181.mp3",
    "neunzehn":  "audio/a0182.mp3",
    "zwanzig":  "audio/a0183.mp3",
    "einundzwanzig":  "audio/a0184.mp3",
    "zweiundzwanzig":  "audio/a0185.mp3",
    "dreißig":  "audio/a0186.mp3",
    "vierzig":  "audio/a0187.mp3",
    "fünfzig":  "audio/a0188.mp3",
    "sechzig":  "audio/a0189.mp3",
    "siebzig":  "audio/a0190.mp3",
    "achtzig":  "audio/a0191.mp3",
    "neunzig":  "audio/a0192.mp3",
    "hundert":  "audio/a0193.mp3",
    "tausend":  "audio/a0194.mp3",
    "Montag":  "audio/a0195.mp3",
    "Dienstag":  "audio/a0196.mp3",
    "Mittwoch":  "audio/a0197.mp3",
    "Donnerstag":  "audio/a0198.mp3",
    "Freitag":  "audio/a0199.mp3",
    "Samstag":  "audio/a0200.mp3",
    "Sonntag":  "audio/a0201.mp3",
    "Januar":  "audio/a0202.mp3",
    "Februar":  "audio/a0203.mp3",
    "März":  "audio/a0204.mp3",
    "April":  "audio/a0205.mp3",
    "Mai":  "audio/a0206.mp3",
    "Juni":  "audio/a0207.mp3",
    "Juli":  "audio/a0208.mp3",
    "August":  "audio/a0209.mp3",
    "September":  "audio/a0210.mp3",
    "Oktober":  "audio/a0211.mp3",
    "November":  "audio/a0212.mp3",
    "Dezember":  "audio/a0213.mp3",
    "Wie spät ist es?":  "audio/a0214.mp3",
    "Es ist zehn Uhr.":  "audio/a0215.mp3",
    "Mittag":  "audio/a0216.mp3",
    "Mitternacht":  "audio/a0217.mp3",
    "der Morgen":  "audio/a0218.mp3",
    "der Nachmittag":  "audio/a0219.mp3",
    "der Abend":  "audio/a0220.mp3",
    "heute":  "audio/a0221.mp3",
    "morgen":  "audio/a0222.mp3",
    "gestern":  "audio/a0223.mp3",
    "jetzt":  "audio/a0224.mp3",
    "Guten Tag, ich hätte gerne einen Stellplatz für ein Wohnmobil.":  "audio/a0095.mp3",
    "Haben Sie einen Platz für unseren Wohnwagen?":  "audio/a0096.mp3",
    "Guten Tag, sehr gut! Waren Sie schon einmal bei uns?":  "audio/a0097.mp3",
    "Haben Sie eine ACSI-, ADAC- oder ANWB-Karte?":  "audio/a0098.mp3",
    "Wie ist Ihr Nachname, bitte?":  "audio/a0099.mp3",
    "Hier ist der Plan mit den freien Plätzen. Wenn eine Nummer eingetragen ist, ist der Platz frei. Ohne Nummer ist er belegt.":  "audio/a0244.mp3",
    "Nehmen Sie den Plan, gehen Sie zu Fuß hin, und kommen Sie zurück, wenn Sie zwei ausgewählt haben.":  "audio/a0101.mp3",
    "Hier ist der Bereich für die ACSI-Stellplätze.":  "audio/a0102.mp3",
    "Ich behalte Ihre ACSI-Karte oder Ihren Ausweis, und Sie zahlen am Tag vor Ihrer Abreise. So zahlen Sie nur die Tage, die Sie bleiben!":  "audio/a0103.mp3",
    "Wie viele Erwachsene und wie viele Kinder sind Sie?":  "audio/a0104.mp3",
    "Haben Sie einen Hund dabei?":  "audio/a0105.mp3",
    "Ich brauche bitte Ihr Kennzeichen.":  "audio/a0106.mp3",
    "Ihre Telefonnummer, bitte?":  "audio/a0107.mp3",
    "Ihre E-Mail-Adresse?":  "audio/a0108.mp3",
    "Und Ihre Wohnadresse, bitte?":  "audio/a0109.mp3",
    "Wir sind hier an der Rezeption des Beach Garden. Direkt daneben liegt der Nouvelle Floride und gegenüber der Charlemagne. Mit Ihren Armbändern haben Sie Zugang zu allen drei Campingplätzen!":  "audio/a0245.mp3",
    "Hier sperrt eine Tür den Zugang zum Strand. Sie geben diesen Code ein, um sie zu öffnen. Sie funktioniert von sieben bis zweiundzwanzig Uhr.":  "audio/a0111.mp3",
    "Ich empfehle Ihnen, die App Tipiz herunterzuladen. Sie geben dieses Passwort ein. Darin finden Sie das Animationsprogramm, die Öffnungszeiten, die Menüs, das Wetter und mehr.":  "audio/a0112.mp3",
    "Hier sind Ihre Armbänder: diese für die Erwachsenen, und diese für die Minderjährigen.":  "audio/a0113.mp3",
    "Und diese Vignette legen Sie bitte auf das Armaturenbrett Ihres Fahrzeugs.":  "audio/a0114.mp3",
    "Haben Sie noch Fragen?":  "audio/a0115.mp3",
    "Perfekt! Ich wünsche Ihnen einen schönen Aufenthalt bei uns.":  "audio/a0116.mp3",
    "Guten Morgen, wir reisen heute ab.":  "audio/a0117.mp3",
    "Wir möchten gerne auschecken.":  "audio/a0118.mp3",
    "Guten Morgen! Ich hoffe, Sie hatten einen schönen Aufenthalt. Haben Sie das Mobilheim aufgeräumt?":  "audio/a0119.mp3",
    "Haben Sie die Endreinigung gemacht, oder sollen wir das übernehmen?":  "audio/a0120.mp3",
    "Können Sie mir bitte die Armbänder und den Schlüssel zurückgeben?":  "audio/a0121.mp3",
    "Alles ist in Ordnung, Sie bekommen Ihre Kaution zurück.":  "audio/a0122.mp3",
    "Vielen Dank für alles, es war wunderschön!":  "audio/a0123.mp3",
    "Können wir schon für nächstes Jahr buchen?":  "audio/a0124.mp3",
    "Vielen Dank für Ihren Besuch und gute Heimreise! Bis nächstes Jahr, hoffentlich.":  "audio/a0125.mp3",
    "Die Nachbarn sind viel zu laut, wir können nicht schlafen.":  "audio/a0126.mp3",
    "Können Sie bitte etwas unternehmen?":  "audio/a0127.mp3",
    "Es tut mir wirklich leid wegen der Störung. Ich kümmere mich sofort darum.":  "audio/a0246.mp3",
    "Ab zweiundzwanzig Uhr gilt bei uns Nachtruhe. Darf ich Sie bitten, leiser zu sein?":  "audio/a0129.mp3",
    "Es ist erledigt, sie werden Rücksicht nehmen. Kommen Sie gerne wieder zu mir, falls es noch einmal passiert.":  "audio/a0130.mp3",
    "Die Klimaanlage funktioniert nicht.":  "audio/a0131.mp3",
    "Oh, das tut mir leid. Können Sie mir Ihre Stellplatznummer geben?":  "audio/a0132.mp3",
    "Ich schicke Ihnen so schnell wie möglich einen Techniker vorbei.":  "audio/a0133.mp3",
    "Er kommt innerhalb einer Stunde vorbei.":  "audio/a0134.mp3",
    "Funktioniert jetzt wieder alles?":  "audio/a0135.mp3",
    "Entschuldigen Sie bitte die Unannehmlichkeiten.":  "audio/a0136.mp3",
    "Camping Beach Garden, guten Tag! Was kann ich für Sie tun?":  "audio/a0137.mp3",
    "Ich möchte einen Stellplatz reservieren.":  "audio/a0138.mp3",
    "Haben Sie im August noch etwas frei?":  "audio/a0139.mp3",
    "Für welche Daten möchten Sie reservieren?":  "audio/a0140.mp3",
    "Wie viele Personen sind Sie?":  "audio/a0141.mp3",
    "Möchten Sie lieber einen Stellplatz oder ein Mobilheim?":  "audio/a0142.mp3",
    "Der Preis beträgt … Euro pro Nacht. Wir benötigen eine Anzahlung von dreißig Prozent.":  "audio/a0143.mp3",
    "Ich sende Ihnen die Bestätigung per E-Mail. Wie lautet Ihre E-Mail-Adresse?":  "audio/a0144.mp3",
    "Vielen Dank für Ihren Anruf und bis bald im Beach Garden!":  "audio/a0145.mp3",
    "Guten Tag, wir haben eine Reservierung auf den Namen Müller.":  "audio/a0262.mp3",
    "Wir sind gerade angekommen.":  "audio/a0263.mp3",
    "Guten Tag und herzlich willkommen! Auf welchen Namen haben Sie reserviert?":  "audio/a0264.mp3",
    "Haben Sie einen Hund dabei? Dann brauche ich bitte den Impfpass.":  "audio/a0265.mp3",
    "Hier sind Ihre Armbänder. Bitte tragen Sie sie während des ganzen Aufenthalts gut sichtbar am Handgelenk.":  "audio/a0266.mp3",
    "Guten Tag, wir möchten Freunde besuchen, die hier Urlaub machen.":  "audio/a0267.mp3",
    "Dürfen wir auch ins Schwimmbad?":  "audio/a0268.mp3",
    "Gerne! Wie heißen Ihre Freunde, und welche Stellplatznummer haben sie?":  "audio/a0269.mp3",
    "Ich wünsche Ihnen einen schönen Tag!":  "audio/a0270.mp3",
    "Im Badezimmer ist es schmutzig.":  "audio/a0293.mp3",
    "Das tut mir sehr leid. Welche Nummer hat Ihr Mobilheim?":  "audio/a0294.mp3",
    "Ich schicke sofort jemanden zum Putzen vorbei.":  "audio/a0295.mp3",
    "Das wird innerhalb einer Stunde erledigt. Kommen Sie gerne wieder, wenn etwas nicht in Ordnung ist.":  "audio/a0296.mp3",
    "Was gibt es für die Kinder?":  "audio/a0297.mp3",
    "Ja! Heute Abend gibt es um … Uhr eine Show.":  "audio/a0298.mp3",
    "Das ganze Programm finden Sie in der App Tipiz.":  "audio/a0299.mp3",
    "Ich möchte eine Massage buchen.":  "audio/a0300.mp3",
    "Wann hat das Spa geöffnet?":  "audio/a0301.mp3",
    "Für welchen Tag und um wie viel Uhr?":  "audio/a0302.mp3",
    "Ich reserviere Ihnen einen Termin um … Uhr.":  "audio/a0303.mp3",
    "Können wir heute Abend einen Tisch reservieren?":  "audio/a0304.mp3",
    "Ab wann ist das Restaurant geöffnet?":  "audio/a0305.mp3",
    "Natürlich! Für wie viele Personen?":  "audio/a0306.mp3",
    "Notiert: ein Tisch für … Personen um … Uhr.":  "audio/a0307.mp3",
    "Ich wünsche Ihnen einen schönen Abend!":  "audio/a0308.mp3"
};
